name: robolab_x
description: RoboLab-X professional AI-assisted robotics engineering workspace for Android.
publish_to: 'none'
version: 2.0.0+20

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  cupertino_icons: ^1.0.8
  google_sign_in: ^7.2.0
  shared_preferences: ^2.5.3
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
